// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Stathub.Modules.Leagues.Infrastructure.Persistence;

#nullable disable

namespace Stathub.Modules.Leagues.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LeaguesDbContext))]
    [Migration("20260921092657_AddLeagueDiscoveryFields")]
    partial class AddLeagueDiscoveryFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("leagues")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.League", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DataSource")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sport")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("City");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("leagues", "leagues");
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.Stage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("FormatType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("stages", "leagues");
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.StageTiebreakerRule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Criterion")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<Guid>("StageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("stage_tiebreaker_rules", "leagues");
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LeagueId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("tournaments", "leagues");
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.Stage", b =>
                {
                    b.HasOne("Stathub.Modules.Leagues.Domain.Entities.Tournament", null)
                        .WithMany("Stages")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Stathub.Modules.Leagues.Domain.ValueObjects.MatchFormatRule", "MatchFormatRule", b1 =>
                        {
                            b1.Property<Guid>("StageId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("ExtraTimeEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("extra_time_enabled");

                            b1.Property<bool>("PenaltyShootoutEnabled")
                                .HasColumnType("boolean")
                                .HasColumnName("penalty_shootout_enabled");

                            b1.Property<int>("PeriodDurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("period_duration_minutes");

                            b1.Property<int>("PeriodsCount")
                                .HasColumnType("integer")
                                .HasColumnName("periods_count");

                            b1.HasKey("StageId");

                            b1.ToTable("stages", "leagues");

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.OwnsOne("Stathub.Modules.Leagues.Domain.ValueObjects.PointsRule", "PointsRule", b1 =>
                        {
                            b1.Property<Guid>("StageId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DrawPoints")
                                .HasColumnType("integer")
                                .HasColumnName("draw_points");

                            b1.Property<int>("LossPoints")
                                .HasColumnType("integer")
                                .HasColumnName("loss_points");

                            b1.Property<int>("WinPoints")
                                .HasColumnType("integer")
                                .HasColumnName("win_points");

                            b1.HasKey("StageId");

                            b1.ToTable("stages", "leagues");

                            b1.WithOwner()
                                .HasForeignKey("StageId");
                        });

                    b.Navigation("MatchFormatRule")
                        .IsRequired();

                    b.Navigation("PointsRule")
                        .IsRequired();
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.StageTiebreakerRule", b =>
                {
                    b.HasOne("Stathub.Modules.Leagues.Domain.Entities.Stage", null)
                        .WithMany("TiebreakerRules")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.Stage", b =>
                {
                    b.Navigation("TiebreakerRules");
                });

            modelBuilder.Entity("Stathub.Modules.Leagues.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Stages");
                });
#pragma warning restore 612, 618
        }
    }
}
